version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: blog_api_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blog_network

volumes:
  mysql_data:

networks:
  blog_network:
    driver: bridge