version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: selapang_api_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: selapang
      MYSQL_USER: selapang
      MYSQL_PASSWORD: selapang
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - selapang_network

volumes:
  mysql_data:

networks:
  selapang_network:
    driver: bridge