services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080  
      SPRING_DATASOURCE_URL: jdbc:mysql://34.134.92.189:3306/blog
      SPRING_DATASOURCE_USERNAME: blog
      SPRING_DATASOURCE_PASSWORD: Sinaga@2016